name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: ShivangiAhuja
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=%23f48fb1&color_dots=%23ebedf0,%23ffd6e8,%23ffb3d9,%23ff80c8,%23ff4db8
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
