name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: ShivangiAhuja
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=f48fb1&color_dots=#ebedf0,#ffd6e8,#ffb3d9,#ff80c8,#ff4db8
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
